name: Build APK

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: npm install
      - run: npm install @capacitor/core @capacitor/cli @capacitor/android

      # Initialize & Fix White Screen
      - run: npx cap init Hut13 com.hut13.app --web-dir dist || true
      - run: sed -i "s/export default defineConfig({/export default defineConfig({ base: '.\/',/" vite.config.ts

      # Build
      - run: npm run build
      - run: rm -rf android
      - run: npx cap add android
      - run: cd android && ./gradlew assembleDebug

      # Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: Hut13-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
